spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/page?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 100
      minimum-idle: 30
      pool-name: HikariConnectionPool

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #    cache-enabled: true
    local-cache-scope: session
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

